import React from 'react';
import { useLocation } from 'react-router-dom';


const Items = () => {
    const location = useLocation();
    const menu = {
        "Veg Soups": {
          "Veg Clear Soup": 80,
          "Veg Coriander Soup": 80,
          "Veg Lemon Coriander Soup": 100,
          "Veg Hot n Sour Soup": 100,
          "Veg Corn Soup": 100,
          "Veg Sweet Corn Soup": 120,
          "Veg Manchow Soup": 120,
          "Veg Tomato Soup": 100,
          "Mixed Veg Soup": 120,
        },
        "Non Veg Soups": {
          "Chicken Pepper Soup": 130,
          "Chicken Corn Soup": 140,
          "Chicken Sweet Corn Soup": 140,
          "Chicken Lemon Coriander": 140,
          "Chicken Hot and Sour Soup": 150,
          "Chicken Manchow Soup": 160,
          "Chicken Clear Soup": 140,
          "Chicken Cream Off Soup": 150,
          "Chicken Dragon Soup": 140,
        },
        "Veg Starters": {
          "Baby Corn Schezwan": 220,
          "Baby Corn Salt & Pepper": 220,
          "Baby Corn Chilly": 200,
          "Baby Corn Manchurian": 200,
          "Baby Corn Garlic": 220,
          "Baby Corn Ginger": 220,
          "Baby Corn Finger": 220,
          "Crispy Corn": 200,
          "Boiled Corn": 140,
          "Corn Salt & Pepper": 180,
          "Mushroom Manchurian": 200,
          "Mushroom 65": 200,
          "Mushroom Chilly": 200,
          "Mushroom Salt & Pepper": 200,
          "Hot Pepper Mushroom": 230,
          "Ginger Mushroom": 220,
          "Paneer 65": 240,
          "Paneer Chilly": 240,
          "Paneer Salt & Pepper": 240,
          "Paneer Manchurian": 260,
          "Dragon Paneer": 260,
          "Schezwan Paneer": 280,
          "Paneer 555": 260,
          "Paneer Majestic(Special)": 260,
          "Golden Fried Paneer(Special)": 260,
          "Paneer Hot Pepper": 230,
          "Veg Manchurian": 200,
          "Mix Veg 8 to 8(Special)": 240,
          "Crispy Veg(Special)": 220,
          "Veg Sangai(Special)": 320,
        },
        "Chicken Starters": {
          "Chicken 999(Special)": 260,
          "Chicken 8 to 8(Special)": 260,
          "Chicken Joint(2)": 180,
          "Dragon Wings": 240,
          "Chilly Wings": 240,
          "Wings 65": 240,
          "Wings Roast": 240,
          "Loose Chicken": 240,
          "Chicken 65": 250,
          "Chilly Chicken": 250,
          "Chicken Manchurian": 250,
          "Chicken Drum Stick": 240,
          "Ginger Chicken": 250,
          "Garlic Chicken": 260,
          "Butter Garlic Chicken(Special)": 280,
          "Pepper Chicken": 260,
          "Schezwan Chicken": 280,
          "Golden Chicken": 280,
          "Lemon Honey Chicken": 280,
          "Majestic Chicken": 280,
          "Chicken 555": 280,
          "Spicy Honey Chicken": 280,
          "Dragon Chicken": 280,
          "Crispy Chicken": 280,
          "Apollo Chicken": 280,
          "Chicken Lollipop": 280,
          "R.R Chicken": 280,
          "Cashew Chicken": 280,
          "Sesmee Chicken": 280,
          "Chicken Sangai": 320,
          "Sizling Chicken": 330,
          "Chicken Fry(Indian)": 220,
          "Liver Fry(Indian)": 180,
        },
        "Mutton Starters": {
          "Mutton Fry(Indian)": 280,
        },
        "Fish Starters": {
          "Black Pepper Fish": 320,
          "Chilly Fish": 270,
          "Fish Manchurian": 280,
          "Dragon Fish": 270,
          "Apollo Fish": 270,
          "Lemon Honey Fish": 280,
          "Lemon Fish": 280,
          "Finger Fish": 300,
          "Fish Fry(Indian)": 240,
        },
        "Prawn Starters": {
          "Loose Prawns(Special)": 340,
          "Chilly Prawns": 320,
          "Prawns Manchurian": 320,
          "Lemon Prawns": 330,
          "Prawns 65": 330,
          "Golden Prawns": 330,
          "Dragon Prawns": 330,
          "Lemon Honey Prawns": 350,
          "Prawns Fry(Indian)": 300,
        },
        "Egg": {
          "Omlet": 60,
          "Egg Bhurji": 100,
          "Egg Masala": 150,
          "Egg 65": 220,
          "Chilli Egg": 220,
          "Boiled Egg": 20,
        },
        "Veg Biryani": {
          "Biryani Rice": 160,
          "Veg Dum Biryani": 200,
          "Mushroom Biryani": 220,
          "Cashew Biryani": 280,
          "Paneer Biryani": 260,
          "SPL Veg Biryani": 300,
        },
        "Non Veg Biryani": {
          "Chicken Fry Piece Biryani Half": 180,
          "Chicken Fry Piee Biryani": 300,
          "Chicken Dum Biryani Half": 160,
          "Chicken Dum Biryani": 280,
          "Chicken Joint Biryani": 300,
          "Chicken Boneless Biryani": 340,
          "Chicken Tangdi Biryani": 340,
          "Chicken DrumStick Biryani": 320,
          "Chicken Ghee Roast": 320,
          "Chicken Moghalai Biryani": 320,
          "Chicken Lolipop Biryani": 320,
          "Pot Biryani(Special)": 320,
          "Donne Biryani(Special)": 300,
          "Dilkush Biryani": 450,
          "Mutton Fry Piece Biryani": 380,
          "Mutton Ghee Roast Biryani": 380,
          "Spl Mutton Biryani": 440,
          "Prawns Biryani": 380,
          "Spl Prawns Biryani": 440,
          "Fish Biryani": 320,
        },
        "Veg Tandoori": {
          "Veg Sheek Kabab": 180,
          "Paneer Tikka": 240,
          "Malai Paneer": 240,
          "Nizami Paneer Tikka": 280,
          "Hara Bara Kabab": 240,
        },
        "Non Veg Tandoori": {
          "Tandori Chicken (1/2)": 280,
          "Tandoori Chicken Full": 480,
          "Achari Tikka": 280,
          "Pudhina Tikka": 280,
          "Chicken Tikka": 280,
          "Pahadi Tikka": 280,
          "Malai Tikka": 280,
          "Tandoori Kabab": 280,
          "Pudhina Kabab": 280,
          "Haryali Kabab": 280,
          "Banjara Kabab": 280,
          "Kalmi Kabab": 280,
          "Achari Kabab": 280,
          "Methi Kabab": 280,
          "Chicken Seek Kabab": 280,
          "Pahadi Kabab": 280,
          "Reshmi Kabab": 280,
          "Tangdi Kabad": 280,
        },
        "Rice Items": {
          "Curd Rice": 120,
          "Plain Rice": 50,
        },
        "Veg Fried Rice": {
          "Jeera Rice": 160,
          "Veg Fried Rice": 180,
          "Gobi Fried Rice": 180,
          "Veg Chilly Garlic": 180,
          "Ghee Rice": 160,
          "Veg Schezwan Fried Rice": 200,
          "Baby Corn Fried": 220,
          "Paneer Fried Rice": 220,
          "Spl Veg Fried Rice": 260,
        },
        "Non Veg Fried Rice": {
          "Egg Fried Rice": 180,
          "Egg Schezwan Fried Rice": 200,
          "Egg Chilly Garlic Fried Rice": 200,
          "Egg Mexican Fried Rice": 200,
          "Chicken Fried Rice": 240,
          "Chicken Chilly Garlic Fried Rice": 240,
          "Chicken Schezwan Fried Rice": 240,
          "Mutton Fried Rice": 280,
          "Mutton Schezwan Fried Rice": 280,
          "Mutton Chilli Garlic Fried Rice": 280,
          "Prawns Fried Rice": 280,
          "Prawns Schezwan Fried Rice": 290,
          "Mixed Fried Rice": 320,
          "Spl Non Veg Fried Rice": 300,
        },
        "Roti Items": {
          "Pulka": 15,
          "Tandoor Roti": 30,
          "Butter Roti": 40,
          "Plain Nan": 40,
          "Butter Nan": 50,
          "Coriander Nan": 50,
          "Mughalai Nan": 80,
          "Garlic Nan": 60,
          "Pudhina Garlic Nan": 60,
          "Methi Parata": 40,
          "Lachha Parata": 50,
          "Plain Kulcha": 40,
          "Butter Kulcha": 40,
          "Potato Kulcha": 60,
          "Masala Kulcha": 70,
        },
        "Veg Currys": {
          "Capsicum Masala": 150,
          "Tomato Curry": 160,
          "Baby Corn Curry": 180,
          "Baby Corn Masala": 180,
          "Baby Corn Kadi": 180,
          "Cashew Curry": 260,
          "Cashew Tomato": 240,
          "Cashew Roast": 240,
          "Cashew Paneer": 260,
          "Cashew Masala": 240,
          "Gobi Masala": 150,
          "Kadai Gobi": 180,
          "Aloo Gobi Masala": 200,
          "Green Peas Masala": 180,
          "Mushroom Curry": 220,
          "Mushroom Masala": 220,
          "Mushroom Kolhapuri": 200,
          "Mushroom Butter Masala": 200,
          "Mushroom Mutter Masala": 220,
          "Mushroom Kadai": 220,
          "Paneer Curry": 220,
          "Paneer Butter Masala": 240,
          "Kadai Paneer": 220,
          "Paneer Begum Bahar": 280,
          "Methi Chaman": 240,
          "Veg Kolhapuri": 180,
          "Veg Kadai": 180,
          "Veg Jaipuri": 200,
          "Veg Kofta": 220,
          "Veg Begum Bahar": 220,
          "Veg Punjabi": 200,
          "Veg Dopyaza": 200,
          "Mix Veg Curry": 180,
          "Malai Kofta": 260,
        },
        "Non Veg Currys": {
          "Egg Curry": 150,
          "Chicken Curry": 200,
          "Chicken Boneless Curry": 220,
          "Chicken Kolhapuri": 240,
          "Chicken Dopyaza": 240,
          "Chicken Handi Masala": 250,
          "Tangdi Masala": 280,
          "Chicken Kheema Masala": 320,
          "Chicken Afghani": 320,
          "Chicken Pakoda OIL FRY KEBAB": 250,
          "Chicken Tikka Masala": 320,
          "Chicken Chettinand": 280,
          "Butter Chicken": 280,
          "Kadai Chicken": 280,
          "Murg Musallam (1/2)": 370,
          "Murg Musallam (Full)": 700,
          "Mutton Curry": 320,
          "Mutton Kadai": 320,
          "Mutton Kolhapuri": 320,
          "Mutton Masala": 320,
          "Chilli Mutton Masala": 320,
          "Mutton Rogan Juice": 340,
          "Mutton Ghee Roast": 340,
          "Prawns Curry": 320,
          "Prawns Kadai": 320,
          "Prawns Masala": 320,
          "Prawns Butter Masala": 340,
          "Fish Curry": 240,
          "Fish Kadai": 240,
          "Fish Kolhapuri": 240,
          "Fish Masala": 250,
          "Fish Butter Masala": 260,
          "Tomato Fish Masala": 260,
        },
        "Desserts": {
          "Apricot Delight": 80,
          "Double Ka Meetha": 80,
          "Kaddu Ki Kheer": 80,
          "Arabian Pudding": 80,
          "Malai Pudding": 80,
        },
      };
      
      const { clickedName } = location.state || {};

      console.log(clickedName)
    return (
        <div className='itemC ' data-aos='slide-down' data-aos-duration='1000'>
            <h3 className='text-center fs-1 '>{clickedName}</h3>
            <div className='container fs-5 '>
                <table className='border' cellPadding="10" style={{ width: '100%', margin: '20px auto', textAlign: 'left' }}>

                    <thead className='fs-3 text-center'>
                        <tr className='border-bottom'>
                            <th>S.No</th>
                            <th>Item Name</th>
                            <th>Price</th>
                        </tr>
                    </thead>
                    <tbody className='text-center'>
                    {
                        
                        Object.entries(menu[clickedName]).map(([item,price],index)=>(
                            <tr key={index}>
                            <td>{index+1}</td>
                            <td >{item}</td>
                            <td>{price}</td>
                            </tr>
                        ))
                    }
                    </tbody>
                </table>
            </div>
        </div>
    );
}

export default Items;
